composite_turb_ensambles.x: main.o funcs.o funcs_turb.o
	g++ main.o funcs.o funcs_turb.o -o composite_turb_ensambles.x

main.o: main.c
	g++ -c main.c

funcs.o: funcs.c
	g++ -c funcs.c

funcs_turb.o: funcs_turb.c
	g++ -c funcs_turb.c
